cat("*** Starting R using .Rprofile generated by PsN ***\n")
cat("Using library path /usr/local/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/PsN_5_2_6/Rlib\n")
.libPaths('/usr/local/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/PsN_5_2_6/Rlib')
